#!/bin/bash

if [ $# -eq 0 ]; then
    GH_WORKFLOW_ID="$(gh run ls -R XieJiSS/git-url-parse-rs -s success -u XieJiSS -w Maturin -L 1 --json 'databaseId' -q '.[].databaseId' | head -n 1)"
else
    GH_WORKFLOW_ID=$1
fi

echo Uploading artifacts generated by workflow $GH_WORKFLOW_ID to pypi...

cd "$(dirname "$0")"/../
poetry run python3 -m twine upload "./artifacts/$GH_WORKFLOW_ID/*"
